### PR TITLE
Create compare fractions with a common denominator challenge

### PR DESCRIPTION
**Pull request by petercollingridge**
I've created an example exercise for Comparing Fractions with a Common Denominator. I don't know if this is the sort of thing you had in mind, so I only made one exercise. I would have liked to be able to use LaTex inside the question text, but I wasn't able to figure out how to.

### CODE REVIEW

**Comment by juandaco** [comment]
Thanks for your contribution. I had to do a manual merge that won't show in Github's Pull request tab. Your contribution is still credited in the [commit history](https://github.com/freeCodeCamp/math-for-programmers-prototype/commits/master) to the project so I'm closing this pull request.

I really like the idea of adding LaTeX expressions to the challenge description because it will improve our pedagogical approach for teaching campers. I'll work on that new feature myself and I'll get back to you when I have a working implementation.

**Comment by juandaco** [comment]
It's now possible to add LaTeX expressions to the challenge descriptions, as you suggested. For better instructions, take a look at the Example Challenge on the [prototype's website](https://freecodecamp.github.io/math-for-programmers-prototype/).

**Comment by petercollingridge** [comment]
Cool, so should I make more exercises like this? Is that style of exercise the sort of thing you want?
 How should I create pull requests so you don't have to manually merge them?

**Comment by juandaco** [comment]
We have a map of the math challenges needed in [this folder](https://github.com/freeCodeCamp/freeCodeCamp/tree/staging/seed/math-challenges), so you can choose your topic of interest. I'll be porting those to this project.

For the time being, I would advice you to focus on the pedagogical part of the challenges and not on writing the tests, because we're moving away from Regular Expressions to a more robust system. You should only **add the message part of the test**, and once the system is finished we'll comeback and do the test writing.

About the pull request, I'm sort of a novice when it comes to git, so maybe in the future we'll have clearer instructions (or I'll learn to do it correctly).

**Comment by petercollingridge** [comment]
Great, that makes a lot of sense. I'm glad to hear you're moving away from Regex. I've done some work making Khan Academy exercises - they used to use regex, but quickly realised they're not expressive enough for dealing with a lot of answers (if we want to accept fractions and decimal answers to varying degrees of simplification).

**Pull request closed without merging**
